font_family      Fira Code
bold_font        Fira Code Bold
italic_font      Fira Code Italic
font_size        14
scrollback_lines 10000
remember_window_size  yes
initial_window_width  80
initial_window_height 20
background #1B1B1B
