font_family      FiraCode Nerd Font
bold_font        FiraCode Nerd Font Bold
italic_font      FiraCode Nerd Font Italic
font_size        14
scrollback_lines 10000
remember_window_size  yes
initial_window_width  80
initial_window_height 20
background #1B1B1B
cursor #C75C91
cursor_text_color #FFFFFF
cursor_blink_interval 0
clipboard_control write-clipboard write-primary no-append
map kitty_mod+left no_op
map kitty_mod+right no_op

include ${HOME}/kitty.conf.local
