k9s:
  clusters:
    arn:aws:eks:us-east-1:565317756671:cluster/eks-production-us-east-1: &verumex
      namespace:
        active: verumex
        # With this set, the favorites list won't be updated as you switch namespaces
        lockFavorites: true
        favorites:
          - verumex
          - kube-system
      view:
        active: po
      featureGates:
        # Toggles NodeShell support. Allow K9s to shell into nodes if needed. Default false.
        nodeShell: true
      shellPod:
        image: busybox:1.35.0
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
    arn:aws:eks:us-east-1:385970127662:cluster/eks-staging-us-east-1: *verumex
