k9s:
  refreshRate: 2
  maxConnRetry: 3
  readOnly: false
  noExitOnCtrlC: false
  skipLatestRevCheck: false

  ui:
    headless: false
    logoless: true
    crumbsless: false
    noIcons: false
    enableMouse: false
    skin: onedark

  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreen: false
    textWrap: false
    showTime: false

  shellPod: &shellpod
    image: busybox:1.36.1
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi

  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
